/** OpenAI strict JSON schema for product vision analysis */
export const PRODUCT_DESCRIPTION_VISION_JSON_SCHEMA = {
  type: "object",
  additionalProperties: false,
  properties: {
    descriptionRu: { type: "string" },
    shortAiSummaryEn: { type: "string" },
    categoryContext: {
      type: "string",
      enum: ["clothing", "lingerie", "jewelry", "general"],
    },
    productCategory: {
      type: "string",
      enum: ["auto", "tops", "bottoms", "one-pieces"],
    },
    sourcePresentation: {
      type: "string",
      enum: ["on-model", "flat-lay", "unknown"],
    },
    garmentPhotoType: {
      type: "string",
      enum: ["auto", "model", "flat-lay"],
    },
    setType: {
      type: "string",
      enum: [
        "bra_brief_set",
        "bra_only",
        "bottoms_only",
        "dress",
        "top",
        "bottom",
        "unknown",
      ],
    },
    lingerieSetType: {
      type: "string",
      enum: [
        "bra_brief_set",
        "bra_only",
        "brief_only",
        "bodysuit",
        "teddy",
        "corset",
        "swimsuit_one_piece",
        "bikini_set",
        "unknown",
      ],
    },
    lingerieSetTypeConfidence: { type: "number" },
    lingerieSetTypeReason: { type: "string" },
    baseColor: { type: ["string", "null"] },
    accentColors: { type: "array", items: { type: "string" } },
    pattern: { type: ["string", "null"] },
    materials: { type: "array", items: { type: "string" } },
    bra: {
      type: "object",
      additionalProperties: false,
      properties: {
        present: { type: "boolean" },
        style: { type: ["string", "null"] },
        cupShape: { type: ["string", "null"] },
        straps: { type: ["string", "null"] },
      },
      required: ["present", "style", "cupShape", "straps"],
    },
    bottoms: {
      type: "object",
      additionalProperties: false,
      properties: {
        present: { type: "boolean" },
        style: { type: ["string", "null"] },
        rise: { type: ["string", "null"] },
      },
      required: ["present", "style", "rise"],
    },
    mustPreserve: { type: "array", items: { type: "string" } },
    fitNotes: { type: "array", items: { type: "string" } },
    warnings: { type: "array", items: { type: "string" } },
    confidence: { type: "number" },
    sourceModel: {
      type: ["object", "null"],
      additionalProperties: false,
      properties: {
        bodyType: { type: ["string", "null"] },
        sizeClass: {
          type: ["string", "null"],
          enum: [
            "petite",
            "slim",
            "standard",
            "curvy",
            "plus-size",
            "xl",
            "2xl",
            "unknown",
            null,
          ],
        },
        pose: { type: ["string", "null"] },
        poseRu: { type: ["string", "null"] },
        crop: {
          type: ["string", "null"],
          enum: [
            "full-body",
            "upper-body",
            "waist-up",
            "upper-thigh",
            "close-up",
            "unknown",
            null,
          ],
        },
        cameraAngle: { type: ["string", "null"] },
        handsPosition: { type: ["string", "null"] },
        framing: { type: ["string", "null"] },
        bodyVisibility: { type: ["string", "null"] },
        descriptionRu: { type: ["string", "null"] },
        promptEn: { type: ["string", "null"] },
      },
      required: [
        "bodyType",
        "sizeClass",
        "pose",
        "poseRu",
        "crop",
        "cameraAngle",
        "handsPosition",
        "framing",
        "bodyVisibility",
        "descriptionRu",
        "promptEn",
      ],
    },
  },
  required: [
    "descriptionRu",
    "shortAiSummaryEn",
    "categoryContext",
    "productCategory",
    "sourcePresentation",
    "garmentPhotoType",
    "setType",
    "lingerieSetType",
    "lingerieSetTypeConfidence",
    "lingerieSetTypeReason",
    "baseColor",
    "accentColors",
    "pattern",
    "materials",
    "bra",
    "bottoms",
    "mustPreserve",
    "fitNotes",
    "warnings",
    "confidence",
    "sourceModel",
  ],
} as const;

export const SOURCE_MODEL_VISION_RULES = [
  "If sourcePresentation is on-model, fill sourceModel with body/pose/framing only (technical catalog parameters for a NEW synthetic model).",
  "If sourcePresentation is flat-lay or unknown, sourceModel must be null.",
  "sourceModel: describe body type, size class, pose, crop, camera angle, hands, framing, body visibility — NOT garment colors, lace, patterns, or SKU.",
  "sourceModel.pose: English only — technical pose phrase for image generation; must state front view, back view, or side profile when visible.",
  "sourceModel.cameraAngle: must state whether the model faces the camera, faces away (back view), or is in side profile.",
  "sourceModel.poseRu: Russian only — short merchant-facing pose line (e.g. «сидя в расслабленной позе, корпус слегка повёрнут к камере»). Required when on-model.",
  "sourceModel.promptEn: English only — body proportions, pose, crop, camera, hands, framing. Never black lace, turquoise, floral pattern, bra/brief colors, or product design.",
  "sourceModel.promptEn must end with: do not copy face, identity, tattoos, skin marks, or recognizable features; do not pre-wear the garment.",
  "Do not describe the original person's face, name, identity, or unique marks in sourceModel.",
  "sourceModel.descriptionRu: short Russian note for merchant (body/pose/crop only, no product colors).",
] as const;

export const PRODUCT_VISION_ANALYSIS_RULES = [
  "If garment is visibly worn on a human body, classify sourcePresentation as on-model.",
  "Cropped body without face is still on-model.",
  "Clean background does not mean flat-lay if skin/body is visible.",
  "If skin, breast, belly, waist, hips, arm, hand, shoulder, neck or torso are visible and garment is worn, sourcePresentation must be on-model.",
  "Map garmentPhotoType from sourcePresentation: on-model→model, flat-lay→flat-lay, unknown→auto.",
  "If body, skin, face, limbs, mannequin, or worn garment on person is visible, sourcePresentation must be on-model (even on white catalog background).",
  "If garment lies flat, on hanger, table, or floor without body, sourcePresentation is flat-lay.",
  "Do not treat jewelry, necklace, hand, sofa or background as the main product — main product is the garment.",
  "For lingerie sets use productCategory auto; bra + brief set uses setType bra_brief_set.",
  "For lingerie (categoryContext lingerie) you MUST set lingerieSetType, lingerieSetTypeConfidence (0-1), lingerieSetTypeReason.",
  "lingerieSetType bra_brief_set: separate bra cups/straps AND separate brief/panty with visible skin gap between top and bottom; high-waist brief counts as separate bottom.",
  "lingerieSetType bodysuit/teddy/swimsuit_one_piece: garment visually connects top and bottom with NO visible skin gap; one continuous piece.",
  "lingerieSetType bra_only / brief_only: only one piece of lingerie is the product.",
  "lingerieSetType bikini_set: swim bikini top + bottom as two pieces.",
  "Do not confuse the model's bare skin gap with garment design — if bra band and brief waistband are separate with belly skin visible, it is bra_brief_set NOT bodysuit.",
  "On-model photos: do not treat the model body as part of the garment; classify the garment construction only.",
  "shortAiSummaryEn: dense English tags for AI pipeline (colors, set type, preserve list, on-model vs flat-lay).",
  "mustPreserve: 4-8 English phrases — colors, lace, straps, cup shape, fit details that must not change in try-on/repair.",
  "fitNotes: 3-6 English phrases — fit/silhouette preservation for bust and bottoms.",
  "warnings: include if necklace/props visible but not the product; if worn on body say do not classify as flat-lay.",
  ...SOURCE_MODEL_VISION_RULES,
] as const;
