/** OpenAI strict JSON schema for product vision analysis */
export const PRODUCT_DESCRIPTION_VISION_JSON_SCHEMA = {
  type: "object",
  additionalProperties: false,
  properties: {
    descriptionRu: { type: "string" },
    shortAiSummaryEn: { type: "string" },
    categoryContext: {
      type: "string",
      enum: ["clothing", "lingerie", "jewelry", "general"],
    },
    productCategory: {
      type: "string",
      enum: ["auto", "tops", "bottoms", "one-pieces"],
    },
    sourcePresentation: {
      type: "string",
      enum: ["on-model", "flat-lay", "unknown"],
    },
    garmentPhotoType: {
      type: "string",
      enum: ["auto", "model", "flat-lay"],
    },
    setType: {
      type: "string",
      enum: [
        "bra_brief_set",
        "bra_only",
        "bottoms_only",
        "dress",
        "top",
        "bottom",
        "unknown",
      ],
    },
    baseColor: { type: ["string", "null"] },
    accentColors: { type: "array", items: { type: "string" } },
    pattern: { type: ["string", "null"] },
    materials: { type: "array", items: { type: "string" } },
    bra: {
      type: "object",
      additionalProperties: false,
      properties: {
        present: { type: "boolean" },
        style: { type: ["string", "null"] },
        cupShape: { type: ["string", "null"] },
        straps: { type: ["string", "null"] },
      },
      required: ["present", "style", "cupShape", "straps"],
    },
    bottoms: {
      type: "object",
      additionalProperties: false,
      properties: {
        present: { type: "boolean" },
        style: { type: ["string", "null"] },
        rise: { type: ["string", "null"] },
      },
      required: ["present", "style", "rise"],
    },
    mustPreserve: { type: "array", items: { type: "string" } },
    fitNotes: { type: "array", items: { type: "string" } },
    warnings: { type: "array", items: { type: "string" } },
    confidence: { type: "number" },
  },
  required: [
    "descriptionRu",
    "shortAiSummaryEn",
    "categoryContext",
    "productCategory",
    "sourcePresentation",
    "garmentPhotoType",
    "setType",
    "baseColor",
    "accentColors",
    "pattern",
    "materials",
    "bra",
    "bottoms",
    "mustPreserve",
    "fitNotes",
    "warnings",
    "confidence",
  ],
} as const;

export const PRODUCT_VISION_ANALYSIS_RULES = [
  "If garment is visibly worn on a human body, classify sourcePresentation as on-model.",
  "Cropped body without face is still on-model.",
  "Clean background does not mean flat-lay if skin/body is visible.",
  "If skin, breast, belly, waist, hips, arm, hand, shoulder, neck or torso are visible and garment is worn, sourcePresentation must be on-model.",
  "For on-model lingerie, garmentPhotoType should be model or auto, not flat-lay.",
  "Do not treat jewelry, necklace, hand, sofa or background as the main product — main product is the garment.",
  "For lingerie sets use productCategory one-pieces; bra + brief set uses setType bra_brief_set.",
  "shortAiSummaryEn: dense English tags for AI pipeline (colors, set type, preserve list, on-model vs flat-lay).",
  "mustPreserve: 4-8 English phrases — colors, lace, straps, cup shape, fit details that must not change in try-on/repair.",
  "fitNotes: 3-6 English phrases — fit/silhouette preservation for bust and bottoms.",
  "warnings: include if necklace/props visible but not the product; if worn on body say do not classify as flat-lay.",
] as const;
