/** @deprecated Import from `@/lib/ai/videoCatalog` */
export {
  VIDEO_MODELS,
  VIDEO_VARIANTS,
  VIDEO_PROVIDERS,
  DEFAULT_VARIANT_BY_PROVIDER,
  VARIANTS_BY_PROVIDER,
  getVideoModel,
  getVideoVariant,
  estimateVideoCostUsd,
  mapSaasQualityToVideoApi,
  clampVideoSettingsToVariant,
  getProviderForVariant,
  type VideoModelKey,
  type VideoVariantId,
  type VideoProviderId,
  type VideoQuality,
  type VideoAspectRatio,
  type VideoMotionPreset,
  type KlingMotionOrientation,
} from "@/lib/ai/videoCatalog";
